# Generated by Django 6.0.3 on 2026-03-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_product_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
